### ISSUE TITLE
Convert a full frame COCO-like dataset to a tiled one

### ISSUE THREAD

**Issue by songwsx** [tyomj/product_detection#1]
Thank you so much for your sharing.But I'm having some problems when I run the second step.
` 2. Convert a full frame COCO-like dataset to a tiled one`

## First problem
![image](https://user-images.githubusercontent.com/32413719/85837930-56c1b180-b7cb-11ea-8fe0-25e915cf0026.png)

I fixed this by modifying the following line of code
`tiles = split_on_tiles(img, bboxes, **vars(args))`

## Second problem
![image](https://user-images.githubusercontent.com/32413719/85838188-ce8fdc00-b7cb-11ea-9565-76524c71bf0b.png)
How can i solve this problem?Thanks

**Comment by tyomj** [comment]
Hi! 
Thanks for reporting the error. 
Indeed, I haven't tested this script after refactoring. 
Fixed [here](https://github.com/tyomj/product_detection/commit/380cfdd7eb581971649857132080d19e7a7f698d)
