### ISSUE TITLE
Can you share your pretrained models? 

### ISSUE THREAD

**Issue by wjtan99** [tyomj/product_detection#2]
Particularly the one for your final best submission. 
Thanks a lot for sharing your great work.

**Comment by alextaymx** [comment]
Hi there , do u have the pretrained models ?

**Comment by tyomj** [comment]
Hey guys, sorry for the delay. Here are the [weights](https://drive.google.com/file/d/159p_RZxjLkRjY_jzhaDn-mE2lvFTboRS/view?usp=sharing) and a corresponding training [log](https://drive.google.com/file/d/1tcRrpWbRftqfovuW2gqWMCKrqRzH8d8g/view?usp=sharing).

**Comment by sainivedh19pt** [comment]
> Hey guys, sorry for the delay. Here are the [weights](https://drive.google.com/file/d/159p_RZxjLkRjY_jzhaDn-mE2lvFTboRS/view?usp=sharing) and a corresponding training [log](https://drive.google.com/file/d/1tcRrpWbRftqfovuW2gqWMCKrqRzH8d8g/view?usp=sharing).

Hi @tyomj , The above link doesn't work anymore. Could you please update the weights
Thanks a lot for sharing your work.

**Comment by xinliqingpi** [comment]
link lost
