### ISSUE TITLE
Asking question: Is counting available.

### ISSUE THREAD

**Issue by Nhatcao99** [tyomj/product_detection#3]
I haven't run the code yet but as mentioned in the paper, the method perform quite well with counting also. I want to know if counting result has also available in the code yet?

**Comment by tyomj** [comment]
@Nhatcao99 Despite count is not a target metric for the challenge, one may also get this information by simply calculating the number of bounding boxes (with the score above some threshold, that you can empirically tune on the test data) model outputs for each image.

**Comment by Nhatcao99** [comment]
> @Nhatcao99 Despite count is not a target metric for the challenge, one may also get this information by simply calculating the number of bounding boxes (with the score above some threshold, that you can empirically tune on the test data) model outputs for each image.

Thank you
