### ISSUE TITLE
mmdetection reproducibility

### ISSUE THREAD

**Issue by ananzeng** [tyomj/product_detection#4]
hi thanks your research,first I want apologize my poor english,when I run mmdetection, I encountered a situation,I get different result in same config,I want to ask can you get the same result in mmdetection?
if you can't get the same result,How did the numbers(some like mAP,AP0.5) on the paper come from?Is it training multiple times to get the average?
thank you

**Comment by tyomj** [comment]
@ananzeng 
Hi,
the best results published were obtained by using [this](https://github.com/tyomj/product_detection/blob/master/configs/sku110k/sku110k_faster_rcnn_r50_fpn_anchor_1x_4tiles_test_half_res.py) config. No TTA or ensembling was used.
You may also find [this](https://github.com/tyomj/product_detection/issues/2#issuecomment-774687585) answer with training logs helpful for comparison.
