### ISSUE TITLE
Tile-combine

### ISSUE THREAD

**Issue by Abeni18** [tyomj/product_detection#5]
Thank you for the work. 
My question is for the tile-combine option, I assume there is a step where the tiled images predicted JSON file labels need to be combined into one JSON file label corresponding to the original image size.  Where is that script located?
 I am not able to find it. 

The soonest response is highly appreciated. 
Thank you!

**Comment by Abeni18** [comment]
Or is it like, once the model is trained on the tiled image, during inference we use the original size image without tiling?

**Comment by tyomj** [comment]
@Abeni18 
Your last guess was right, here in the [config](https://github.com/tyomj/product_detection/blob/master/configs/sku110k/sku110k_faster_rcnn_r50_fpn_anchor_1x_4tiles_test_half_res.py#L117) you may see resolutions. Sorry for the long response.

**Comment by Abeni18** [comment]
Got it thanks
